
#!/usr/bin/env python
# Generated by pykdeuic4 from ID3EncodingConverterGuessingSetup.ui on Sun Apr 13 16:52:09 2008
#
# WARNING! All changes to this file will be lost.
from PyKDE4 import kdecore
from PyKDE4 import kdeui
from PyQt4 import QtCore, QtGui
from PyKDE4.kio import KUrlRequester
from PyKDE4.kdeui import KEditListBox

class Ui_EncodingGuessing(object):
    def setupUi(self, EncodingGuessing):
        EncodingGuessing.setObjectName("EncodingGuessing")
        EncodingGuessing.resize(QtCore.QSize(QtCore.QRect(0,0,508,328).size()).expandedTo(EncodingGuessing.minimumSizeHint()))

        self.vboxlayout = QtGui.QVBoxLayout(EncodingGuessing)
        self.vboxlayout.setObjectName("vboxlayout")

        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName("gridlayout")

        self.label = QtGui.QLabel(EncodingGuessing)
        self.label.setObjectName("label")
        self.gridlayout.addWidget(self.label,1,0,1,1)

        self.kcfg_textcat_LM_path = KUrlRequester(EncodingGuessing)
        self.kcfg_textcat_LM_path.setObjectName("kcfg_textcat_LM_path")
        self.gridlayout.addWidget(self.kcfg_textcat_LM_path,1,1,1,1)

        self.kcfg_language_encoding_pref = KEditListBox(EncodingGuessing)
        self.kcfg_language_encoding_pref.setObjectName("kcfg_language_encoding_pref")
        self.gridlayout.addWidget(self.kcfg_language_encoding_pref,0,1,1,1)

        self.label_2 = QtGui.QLabel(EncodingGuessing)
        self.label_2.setObjectName("label_2")
        self.gridlayout.addWidget(self.label_2,0,0,1,1)

        self.label_3 = QtGui.QLabel(EncodingGuessing)
        self.label_3.setObjectName("label_3")
        self.gridlayout.addWidget(self.label_3,2,0,1,1)

        self.vboxlayout1 = QtGui.QVBoxLayout()
        self.vboxlayout1.setObjectName("vboxlayout1")

        self.checkBox = QtGui.QCheckBox(EncodingGuessing)
        self.checkBox.setObjectName("checkBox")
        self.vboxlayout1.addWidget(self.checkBox)

        self.label_4 = QtGui.QLabel(EncodingGuessing)
        self.label_4.setObjectName("label_4")
        self.vboxlayout1.addWidget(self.label_4)

        self.logurl = KUrlRequester(EncodingGuessing)
        self.logurl.setObjectName("logurl")
        self.vboxlayout1.addWidget(self.logurl)
        self.gridlayout.addLayout(self.vboxlayout1,2,1,1,1)
        self.vboxlayout.addLayout(self.gridlayout)
        self.label.setBuddy(self.kcfg_textcat_LM_path)
        self.label_4.setBuddy(self.logurl)

        self.retranslateUi(EncodingGuessing)
        QtCore.QMetaObject.connectSlotsByName(EncodingGuessing)

    def retranslateUi(self, EncodingGuessing):
        EncodingGuessing.setWindowTitle(kdecore.i18n("Form"))
        self.label.setText(kdecore.i18n("&Textcat path"))
        self.label_2.setText(kdecore.i18n("Preferred encodings"))
        self.label_3.setText(kdecore.i18n("Logging"))
        self.checkBox.setText(kdecore.i18n("&Save log"))
        self.label_4.setText(kdecore.i18n("Log &file"))

